# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_AddSignalWindow.ui'
#
# Created: Mon Jul 06 14:45:08 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_AddSignalWindow(object):
    def setupUi(self, AddSignalWindow):
        AddSignalWindow.setObjectName(_fromUtf8("AddSignalWindow"))
        AddSignalWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(AddSignalWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.radioButton_select_all_variables = QtGui.QRadioButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_select_all_variables.sizePolicy().hasHeightForWidth())
        self.radioButton_select_all_variables.setSizePolicy(sizePolicy)
        self.radioButton_select_all_variables.setMinimumSize(QtCore.QSize(0, 20))
        self.radioButton_select_all_variables.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_select_all_variables.setFont(font)
        self.radioButton_select_all_variables.setObjectName(_fromUtf8("radioButton_select_all_variables"))
        self.gridLayout_2.addWidget(self.radioButton_select_all_variables, 6, 7, 1, 1)
        self.label_time_unit = QtGui.QLabel(self.centralwidget)
        self.label_time_unit.setMinimumSize(QtCore.QSize(0, 20))
        self.label_time_unit.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_time_unit.setFont(font)
        self.label_time_unit.setIndent(10)
        self.label_time_unit.setObjectName(_fromUtf8("label_time_unit"))
        self.gridLayout_2.addWidget(self.label_time_unit, 3, 0, 1, 2)
        self.lineEdit_time_unit = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_time_unit.sizePolicy().hasHeightForWidth())
        self.lineEdit_time_unit.setSizePolicy(sizePolicy)
        self.lineEdit_time_unit.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_time_unit.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_time_unit.setFont(font)
        self.lineEdit_time_unit.setObjectName(_fromUtf8("lineEdit_time_unit"))
        self.gridLayout_2.addWidget(self.lineEdit_time_unit, 3, 2, 1, 1)
        self.label_select_variables = QtGui.QLabel(self.centralwidget)
        self.label_select_variables.setMinimumSize(QtCore.QSize(0, 20))
        self.label_select_variables.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_select_variables.setFont(font)
        self.label_select_variables.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_select_variables.setIndent(10)
        self.label_select_variables.setObjectName(_fromUtf8("label_select_variables"))
        self.gridLayout_2.addWidget(self.label_select_variables, 6, 1, 1, 6)
        self.label_choose_signal = QtGui.QLabel(self.centralwidget)
        self.label_choose_signal.setMinimumSize(QtCore.QSize(0, 20))
        self.label_choose_signal.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_choose_signal.setFont(font)
        self.label_choose_signal.setMargin(0)
        self.label_choose_signal.setIndent(10)
        self.label_choose_signal.setObjectName(_fromUtf8("label_choose_signal"))
        self.gridLayout_2.addWidget(self.label_choose_signal, 0, 0, 1, 7)
        self.pushButton_save_signal = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_save_signal.sizePolicy().hasHeightForWidth())
        self.pushButton_save_signal.setSizePolicy(sizePolicy)
        self.pushButton_save_signal.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_save_signal.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_save_signal.setFont(font)
        self.pushButton_save_signal.setObjectName(_fromUtf8("pushButton_save_signal"))
        self.gridLayout_2.addWidget(self.pushButton_save_signal, 12, 7, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_signal_preview = QtGui.QLabel(self.centralwidget)
        self.label_signal_preview.setMinimumSize(QtCore.QSize(0, 20))
        self.label_signal_preview.setMaximumSize(QtCore.QSize(16777215, 140))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_signal_preview.setFont(font)
        self.label_signal_preview.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_signal_preview.setMargin(0)
        self.label_signal_preview.setIndent(10)
        self.label_signal_preview.setObjectName(_fromUtf8("label_signal_preview"))
        self.gridLayout_2.addWidget(self.label_signal_preview, 7, 0, 1, 1, QtCore.Qt.AlignTop)
        self.pushButton_visualize = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_visualize.sizePolicy().hasHeightForWidth())
        self.pushButton_visualize.setSizePolicy(sizePolicy)
        self.pushButton_visualize.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_visualize.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_visualize.setFont(font)
        self.pushButton_visualize.setObjectName(_fromUtf8("pushButton_visualize"))
        self.gridLayout_2.addWidget(self.pushButton_visualize, 11, 3, 1, 2, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 2, 6, 1, 1)
        self.pushButton_browse = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_browse.sizePolicy().hasHeightForWidth())
        self.pushButton_browse.setSizePolicy(sizePolicy)
        self.pushButton_browse.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_browse.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_browse.setFont(font)
        self.pushButton_browse.setObjectName(_fromUtf8("pushButton_browse"))
        self.gridLayout_2.addWidget(self.pushButton_browse, 1, 6, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(10, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_2.addItem(spacerItem2, 6, 8, 7, 1)
        self.lineEdit_file_path = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_file_path.sizePolicy().hasHeightForWidth())
        self.lineEdit_file_path.setSizePolicy(sizePolicy)
        self.lineEdit_file_path.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_file_path.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_file_path.setFont(font)
        self.lineEdit_file_path.setText(_fromUtf8(""))
        self.lineEdit_file_path.setObjectName(_fromUtf8("lineEdit_file_path"))
        self.gridLayout_2.addWidget(self.lineEdit_file_path, 1, 0, 1, 6)
        self.pushButton_import_file = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_import_file.sizePolicy().hasHeightForWidth())
        self.pushButton_import_file.setSizePolicy(sizePolicy)
        self.pushButton_import_file.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_import_file.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_import_file.setFont(font)
        self.pushButton_import_file.setObjectName(_fromUtf8("pushButton_import_file"))
        self.gridLayout_2.addWidget(self.pushButton_import_file, 3, 7, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_2.addItem(spacerItem3, 3, 8, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 1, 8, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 11, 6, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem6, 4, 0, 2, 9)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem7, 10, 6, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem8, 12, 6, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem9, 3, 3, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem10, 3, 4, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_2.addItem(spacerItem11, 2, 8, 1, 1)
        self.lineEdit_signal_name = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_signal_name.sizePolicy().hasHeightForWidth())
        self.lineEdit_signal_name.setSizePolicy(sizePolicy)
        self.lineEdit_signal_name.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_signal_name.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_signal_name.setFont(font)
        self.lineEdit_signal_name.setObjectName(_fromUtf8("lineEdit_signal_name"))
        self.gridLayout_2.addWidget(self.lineEdit_signal_name, 10, 1, 1, 2)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem12, 3, 6, 1, 1)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem13, 10, 3, 1, 1)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem14, 3, 5, 1, 1)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem15, 10, 4, 1, 1)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem16, 10, 5, 1, 1)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem17, 2, 0, 1, 3)
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem18, 2, 7, 1, 1)
        self.label_signal_name = QtGui.QLabel(self.centralwidget)
        self.label_signal_name.setMinimumSize(QtCore.QSize(0, 20))
        self.label_signal_name.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_signal_name.setFont(font)
        self.label_signal_name.setMargin(0)
        self.label_signal_name.setIndent(10)
        self.label_signal_name.setObjectName(_fromUtf8("label_signal_name"))
        self.gridLayout_2.addWidget(self.label_signal_name, 10, 0, 1, 1)
        self.tableWidget_signal_preview = QtGui.QTableWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_signal_preview.sizePolicy().hasHeightForWidth())
        self.tableWidget_signal_preview.setSizePolicy(sizePolicy)
        self.tableWidget_signal_preview.setMinimumSize(QtCore.QSize(0, 20))
        self.tableWidget_signal_preview.setMaximumSize(QtCore.QSize(16777215, 160))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidget_signal_preview.setFont(font)
        self.tableWidget_signal_preview.setAcceptDrops(False)
        self.tableWidget_signal_preview.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget_signal_preview.setObjectName(_fromUtf8("tableWidget_signal_preview"))
        self.tableWidget_signal_preview.setColumnCount(0)
        self.tableWidget_signal_preview.setRowCount(0)
        self.tableWidget_signal_preview.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget_signal_preview.verticalHeader().setMinimumSectionSize(15)
        self.gridLayout_2.addWidget(self.tableWidget_signal_preview, 7, 1, 2, 7)
        spacerItem19 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.gridLayout_2.addItem(spacerItem19, 9, 0, 1, 8)
        spacerItem20 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_2.addItem(spacerItem20, 8, 0, 1, 1)
        self.radioButton_csv_file = QtGui.QRadioButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_csv_file.sizePolicy().hasHeightForWidth())
        self.radioButton_csv_file.setSizePolicy(sizePolicy)
        self.radioButton_csv_file.setMinimumSize(QtCore.QSize(0, 20))
        self.radioButton_csv_file.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_csv_file.setFont(font)
        self.radioButton_csv_file.setChecked(True)
        self.radioButton_csv_file.setAutoExclusive(False)
        self.radioButton_csv_file.setObjectName(_fromUtf8("radioButton_csv_file"))
        self.gridLayout_2.addWidget(self.radioButton_csv_file, 2, 3, 1, 1)
        self.radioButton_csv_ELAN_file = QtGui.QRadioButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_csv_ELAN_file.sizePolicy().hasHeightForWidth())
        self.radioButton_csv_ELAN_file.setSizePolicy(sizePolicy)
        self.radioButton_csv_ELAN_file.setMinimumSize(QtCore.QSize(0, 20))
        self.radioButton_csv_ELAN_file.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_csv_ELAN_file.setFont(font)
        self.radioButton_csv_ELAN_file.setChecked(False)
        self.radioButton_csv_ELAN_file.setAutoExclusive(False)
        self.radioButton_csv_ELAN_file.setObjectName(_fromUtf8("radioButton_csv_ELAN_file"))
        self.gridLayout_2.addWidget(self.radioButton_csv_ELAN_file, 2, 4, 1, 1)
        self.radioButton_mat_file = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_mat_file.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_mat_file.setFont(font)
        self.radioButton_mat_file.setAutoExclusive(False)
        self.radioButton_mat_file.setObjectName(_fromUtf8("radioButton_mat_file"))
        self.gridLayout_2.addWidget(self.radioButton_mat_file, 2, 5, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        AddSignalWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(AddSignalWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        AddSignalWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(AddSignalWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        AddSignalWindow.setStatusBar(self.statusbar)

        self.retranslateUi(AddSignalWindow)
        QtCore.QMetaObject.connectSlotsByName(AddSignalWindow)

    def retranslateUi(self, AddSignalWindow):
        AddSignalWindow.setWindowTitle(_translate("AddSignalWindow", "Add a New Signal", None))
        self.radioButton_select_all_variables.setText(_translate("AddSignalWindow", "Select all", None))
        self.label_time_unit.setText(_translate("AddSignalWindow", "Define time unit of the input signal \n"
"(ex: ms, s ...) :", None))
        self.label_select_variables.setText(_translate("AddSignalWindow", "You can select wanted variables by clicking on columns in the preview \n"
"(press Ctrl for multiple selection)", None))
        self.label_choose_signal.setText(_translate("AddSignalWindow", "Choose the input file for the signal : ", None))
        self.pushButton_save_signal.setText(_translate("AddSignalWindow", "Add", None))
        self.label_signal_preview.setText(_translate("AddSignalWindow", "Input file \n"
"preview: ", None))
        self.pushButton_visualize.setText(_translate("AddSignalWindow", "Visualize", None))
        self.pushButton_browse.setText(_translate("AddSignalWindow", "...", None))
        self.pushButton_import_file.setText(_translate("AddSignalWindow", "Import", None))
        self.label_signal_name.setText(_translate("AddSignalWindow", "Define \n"
"signal\'s name : ", None))
        self.radioButton_csv_file.setText(_translate("AddSignalWindow", ".csv file", None))
        self.radioButton_csv_ELAN_file.setText(_translate("AddSignalWindow", "ELAN .csv file ", None))
        self.radioButton_mat_file.setText(_translate("AddSignalWindow", ".mat file", None))

