# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_EditSignalWindow.ui'
#
# Created: Tue May 26 10:52:48 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_EditSignalWindow(object):
    def setupUi(self, EditSignalWindow):
        EditSignalWindow.setObjectName(_fromUtf8("EditSignalWindow"))
        EditSignalWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setPointSize(10)
        EditSignalWindow.setFont(font)
        EditSignalWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        EditSignalWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        EditSignalWindow.setDocumentMode(False)
        EditSignalWindow.setTabShape(QtGui.QTabWidget.Rounded)
        EditSignalWindow.setDockNestingEnabled(False)
        EditSignalWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtGui.QWidget(EditSignalWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 8, 6, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_2.addItem(spacerItem1, 0, 6, 1, 1)
        self.pushButton_cut_signal = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_cut_signal.sizePolicy().hasHeightForWidth())
        self.pushButton_cut_signal.setSizePolicy(sizePolicy)
        self.pushButton_cut_signal.setObjectName(_fromUtf8("pushButton_cut_signal"))
        self.gridLayout_2.addWidget(self.pushButton_cut_signal, 4, 5, 1, 1)
        self.radioButton_select_all_variables = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_select_all_variables.setMinimumSize(QtCore.QSize(0, 20))
        self.radioButton_select_all_variables.setMaximumSize(QtCore.QSize(16777215, 40))
        self.radioButton_select_all_variables.setObjectName(_fromUtf8("radioButton_select_all_variables"))
        self.gridLayout_2.addWidget(self.radioButton_select_all_variables, 2, 6, 1, 1)
        self.tableWidget_signal_preview = QtGui.QTableWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_signal_preview.sizePolicy().hasHeightForWidth())
        self.tableWidget_signal_preview.setSizePolicy(sizePolicy)
        self.tableWidget_signal_preview.setMinimumSize(QtCore.QSize(0, 20))
        self.tableWidget_signal_preview.setMaximumSize(QtCore.QSize(16777215, 140))
        self.tableWidget_signal_preview.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget_signal_preview.setObjectName(_fromUtf8("tableWidget_signal_preview"))
        self.tableWidget_signal_preview.setColumnCount(0)
        self.tableWidget_signal_preview.setRowCount(0)
        self.gridLayout_2.addWidget(self.tableWidget_signal_preview, 3, 1, 1, 6)
        self.label_variable_edition = QtGui.QLabel(self.centralwidget)
        self.label_variable_edition.setMinimumSize(QtCore.QSize(0, 20))
        self.label_variable_edition.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_variable_edition.setIndent(10)
        self.label_variable_edition.setObjectName(_fromUtf8("label_variable_edition"))
        self.gridLayout_2.addWidget(self.label_variable_edition, 6, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_2.addItem(spacerItem2, 1, 0, 1, 7)
        self.label_signal_edition = QtGui.QLabel(self.centralwidget)
        self.label_signal_edition.setMinimumSize(QtCore.QSize(0, 20))
        self.label_signal_edition.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_signal_edition.setIndent(10)
        self.label_signal_edition.setObjectName(_fromUtf8("label_signal_edition"))
        self.gridLayout_2.addWidget(self.label_signal_edition, 4, 0, 1, 1)
        self.label_selected_signal = QtGui.QLabel(self.centralwidget)
        self.label_selected_signal.setMinimumSize(QtCore.QSize(0, 20))
        self.label_selected_signal.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_selected_signal.setIndent(10)
        self.label_selected_signal.setObjectName(_fromUtf8("label_selected_signal"))
        self.gridLayout_2.addWidget(self.label_selected_signal, 0, 0, 1, 1)
        self.label_signal_preview = QtGui.QLabel(self.centralwidget)
        self.label_signal_preview.setMinimumSize(QtCore.QSize(0, 20))
        self.label_signal_preview.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_signal_preview.setIndent(10)
        self.label_signal_preview.setObjectName(_fromUtf8("label_signal_preview"))
        self.gridLayout_2.addWidget(self.label_signal_preview, 3, 0, 1, 1, QtCore.Qt.AlignTop)
        self.pushButton_interpolate_signal = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_interpolate_signal.sizePolicy().hasHeightForWidth())
        self.pushButton_interpolate_signal.setSizePolicy(sizePolicy)
        self.pushButton_interpolate_signal.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_interpolate_signal.setMaximumSize(QtCore.QSize(100, 40))
        self.pushButton_interpolate_signal.setObjectName(_fromUtf8("pushButton_interpolate_signal"))
        self.gridLayout_2.addWidget(self.pushButton_interpolate_signal, 4, 4, 1, 1)
        self.label_select_variables = QtGui.QLabel(self.centralwidget)
        self.label_select_variables.setMinimumSize(QtCore.QSize(0, 20))
        self.label_select_variables.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_select_variables.setIndent(10)
        self.label_select_variables.setObjectName(_fromUtf8("label_select_variables"))
        self.gridLayout_2.addWidget(self.label_select_variables, 2, 1, 1, 5)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_2.addItem(spacerItem3, 5, 0, 1, 7)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 0, 5, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 0, 1, 1, 1)
        self.pushButton_rename_signal = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_rename_signal.sizePolicy().hasHeightForWidth())
        self.pushButton_rename_signal.setSizePolicy(sizePolicy)
        self.pushButton_rename_signal.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_rename_signal.setMaximumSize(QtCore.QSize(100, 40))
        self.pushButton_rename_signal.setObjectName(_fromUtf8("pushButton_rename_signal"))
        self.gridLayout_2.addWidget(self.pushButton_rename_signal, 4, 2, 1, 1)
        self.pushButton_resample_signal = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_resample_signal.sizePolicy().hasHeightForWidth())
        self.pushButton_resample_signal.setSizePolicy(sizePolicy)
        self.pushButton_resample_signal.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_resample_signal.setMaximumSize(QtCore.QSize(100, 40))
        self.pushButton_resample_signal.setObjectName(_fromUtf8("pushButton_resample_signal"))
        self.gridLayout_2.addWidget(self.pushButton_resample_signal, 4, 3, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_2.addItem(spacerItem6, 7, 0, 1, 7)
        self.label_selected_signal_name = QtGui.QLabel(self.centralwidget)
        self.label_selected_signal_name.setMinimumSize(QtCore.QSize(0, 20))
        self.label_selected_signal_name.setSizeIncrement(QtCore.QSize(0, 40))
        self.label_selected_signal_name.setText(_fromUtf8(""))
        self.label_selected_signal_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_selected_signal_name.setIndent(10)
        self.label_selected_signal_name.setObjectName(_fromUtf8("label_selected_signal_name"))
        self.gridLayout_2.addWidget(self.label_selected_signal_name, 0, 2, 1, 3)
        self.pushButton_rename_variable = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_rename_variable.sizePolicy().hasHeightForWidth())
        self.pushButton_rename_variable.setSizePolicy(sizePolicy)
        self.pushButton_rename_variable.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_rename_variable.setMaximumSize(QtCore.QSize(100, 40))
        self.pushButton_rename_variable.setObjectName(_fromUtf8("pushButton_rename_variable"))
        self.gridLayout_2.addWidget(self.pushButton_rename_variable, 6, 2, 1, 1)
        self.pushButton_apply_changes = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_apply_changes.sizePolicy().hasHeightForWidth())
        self.pushButton_apply_changes.setSizePolicy(sizePolicy)
        self.pushButton_apply_changes.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_apply_changes.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_apply_changes.setFont(font)
        self.pushButton_apply_changes.setObjectName(_fromUtf8("pushButton_apply_changes"))
        self.gridLayout_2.addWidget(self.pushButton_apply_changes, 9, 6, 1, 1, QtCore.Qt.AlignHCenter)
        self.pushButton_convertIntoBinary = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_convertIntoBinary.sizePolicy().hasHeightForWidth())
        self.pushButton_convertIntoBinary.setSizePolicy(sizePolicy)
        self.pushButton_convertIntoBinary.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_convertIntoBinary.setMaximumSize(QtCore.QSize(100, 40))
        self.pushButton_convertIntoBinary.setObjectName(_fromUtf8("pushButton_convertIntoBinary"))
        self.gridLayout_2.addWidget(self.pushButton_convertIntoBinary, 6, 5, 1, 1)
        self.pushButton_normalize_variable = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_normalize_variable.sizePolicy().hasHeightForWidth())
        self.pushButton_normalize_variable.setSizePolicy(sizePolicy)
        self.pushButton_normalize_variable.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_normalize_variable.setMaximumSize(QtCore.QSize(100, 40))
        self.pushButton_normalize_variable.setObjectName(_fromUtf8("pushButton_normalize_variable"))
        self.gridLayout_2.addWidget(self.pushButton_normalize_variable, 6, 4, 1, 1)
        self.pushButton_visualize = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_visualize.sizePolicy().hasHeightForWidth())
        self.pushButton_visualize.setSizePolicy(sizePolicy)
        self.pushButton_visualize.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_visualize.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_visualize.setFont(font)
        self.pushButton_visualize.setObjectName(_fromUtf8("pushButton_visualize"))
        self.gridLayout_2.addWidget(self.pushButton_visualize, 8, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.pushButton_remove_variable = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_remove_variable.sizePolicy().hasHeightForWidth())
        self.pushButton_remove_variable.setSizePolicy(sizePolicy)
        self.pushButton_remove_variable.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_remove_variable.setMaximumSize(QtCore.QSize(100, 40))
        self.pushButton_remove_variable.setObjectName(_fromUtf8("pushButton_remove_variable"))
        self.gridLayout_2.addWidget(self.pushButton_remove_variable, 6, 3, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_2.addItem(spacerItem7, 8, 0, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_2.addItem(spacerItem8, 9, 0, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_2.addItem(spacerItem9, 6, 6, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_2.addItem(spacerItem10, 4, 6, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        EditSignalWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(EditSignalWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        EditSignalWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(EditSignalWindow)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        EditSignalWindow.setStatusBar(self.statusbar)

        self.retranslateUi(EditSignalWindow)
        QtCore.QMetaObject.connectSlotsByName(EditSignalWindow)

    def retranslateUi(self, EditSignalWindow):
        EditSignalWindow.setWindowTitle(_translate("EditSignalWindow", "Edit a Signal", None))
        self.pushButton_cut_signal.setText(_translate("EditSignalWindow", "Cut \n"
"Signal", None))
        self.radioButton_select_all_variables.setText(_translate("EditSignalWindow", "Select all", None))
        self.label_variable_edition.setText(_translate("EditSignalWindow", "Variable Edition : ", None))
        self.label_signal_edition.setText(_translate("EditSignalWindow", "Signal Edition : ", None))
        self.label_selected_signal.setText(_translate("EditSignalWindow", "Selected signal : ", None))
        self.label_signal_preview.setText(_translate("EditSignalWindow", "Signal\'s view : ", None))
        self.pushButton_interpolate_signal.setText(_translate("EditSignalWindow", "Interpolate \n"
"Signal", None))
        self.label_select_variables.setText(_translate("EditSignalWindow", "You can select wanted variables by clicking on columns in the preview \n"
"(press Ctrl for multiple selection)", None))
        self.pushButton_rename_signal.setText(_translate("EditSignalWindow", "Rename \n"
"Signal", None))
        self.pushButton_resample_signal.setText(_translate("EditSignalWindow", "Resample \n"
"Signal", None))
        self.pushButton_rename_variable.setText(_translate("EditSignalWindow", "Rename \n"
"Variable", None))
        self.pushButton_apply_changes.setText(_translate("EditSignalWindow", "Apply \n"
"Changes", None))
        self.pushButton_convertIntoBinary.setText(_translate("EditSignalWindow", "Convert into \n"
"Binary", None))
        self.pushButton_normalize_variable.setText(_translate("EditSignalWindow", "Normalize \n"
"Variable", None))
        self.pushButton_visualize.setText(_translate("EditSignalWindow", "Visualize", None))
        self.pushButton_remove_variable.setText(_translate("EditSignalWindow", "Remove \n"
"variable", None))

