# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_ImportSignalFromELANWindow.ui'
#
# Created: Tue May 26 11:12:27 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ImportSignalFromELANWindow(object):
    def setupUi(self, ImportSignalFromELANWindow):
        ImportSignalFromELANWindow.setObjectName(_fromUtf8("ImportSignalFromELANWindow"))
        ImportSignalFromELANWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setPointSize(10)
        ImportSignalFromELANWindow.setFont(font)
        self.centralwidget = QtGui.QWidget(ImportSignalFromELANWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_2.addItem(spacerItem, 7, 9, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 4, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_2.addItem(spacerItem2, 5, 9, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_2.addItem(spacerItem3, 4, 9, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_2.addItem(spacerItem4, 6, 9, 1, 1)
        self.pushButton_Import = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Import.sizePolicy().hasHeightForWidth())
        self.pushButton_Import.setSizePolicy(sizePolicy)
        self.pushButton_Import.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_Import.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Import.setFont(font)
        self.pushButton_Import.setObjectName(_fromUtf8("pushButton_Import"))
        self.gridLayout_2.addWidget(self.pushButton_Import, 8, 7, 2, 2)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 0, 7, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 0, 6, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 0, 5, 1, 1)
        self.lineEdit_Actor = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Actor.sizePolicy().hasHeightForWidth())
        self.lineEdit_Actor.setSizePolicy(sizePolicy)
        self.lineEdit_Actor.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_Actor.setMaximumSize(QtCore.QSize(16777215, 40))
        self.lineEdit_Actor.setObjectName(_fromUtf8("lineEdit_Actor"))
        self.gridLayout_2.addWidget(self.lineEdit_Actor, 6, 1, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 0, 8, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_2.addItem(spacerItem9, 3, 9, 1, 1)
        self.spinBox_ele_per_second = QtGui.QSpinBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_ele_per_second.sizePolicy().hasHeightForWidth())
        self.spinBox_ele_per_second.setSizePolicy(sizePolicy)
        self.spinBox_ele_per_second.setMinimumSize(QtCore.QSize(0, 20))
        self.spinBox_ele_per_second.setMaximumSize(QtCore.QSize(16777215, 40))
        self.spinBox_ele_per_second.setProperty("value", 1)
        self.spinBox_ele_per_second.setObjectName(_fromUtf8("spinBox_ele_per_second"))
        self.gridLayout_2.addWidget(self.spinBox_ele_per_second, 3, 1, 1, 1)
        self.label_columns_names = QtGui.QLabel(self.centralwidget)
        self.label_columns_names.setMinimumSize(QtCore.QSize(0, 20))
        self.label_columns_names.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_columns_names.setIndent(10)
        self.label_columns_names.setObjectName(_fromUtf8("label_columns_names"))
        self.gridLayout_2.addWidget(self.label_columns_names, 4, 0, 1, 1)
        self.label_actor = QtGui.QLabel(self.centralwidget)
        self.label_actor.setMinimumSize(QtCore.QSize(0, 20))
        self.label_actor.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_actor.setIndent(10)
        self.label_actor.setObjectName(_fromUtf8("label_actor"))
        self.gridLayout_2.addWidget(self.label_actor, 6, 0, 1, 1)
        self.label_action = QtGui.QLabel(self.centralwidget)
        self.label_action.setMinimumSize(QtCore.QSize(0, 20))
        self.label_action.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_action.setIndent(10)
        self.label_action.setObjectName(_fromUtf8("label_action"))
        self.gridLayout_2.addWidget(self.label_action, 7, 0, 1, 1)
        self.listWidget_columns_names = QtGui.QListWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_columns_names.sizePolicy().hasHeightForWidth())
        self.listWidget_columns_names.setSizePolicy(sizePolicy)
        self.listWidget_columns_names.setMinimumSize(QtCore.QSize(0, 20))
        self.listWidget_columns_names.setMaximumSize(QtCore.QSize(16777215, 100))
        self.listWidget_columns_names.setObjectName(_fromUtf8("listWidget_columns_names"))
        self.gridLayout_2.addWidget(self.listWidget_columns_names, 4, 1, 2, 1)
        self.pushButton_removeColumn = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_removeColumn.sizePolicy().hasHeightForWidth())
        self.pushButton_removeColumn.setSizePolicy(sizePolicy)
        self.pushButton_removeColumn.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_removeColumn.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_removeColumn.setObjectName(_fromUtf8("pushButton_removeColumn"))
        self.gridLayout_2.addWidget(self.pushButton_removeColumn, 5, 2, 1, 1)
        self.pushButton_addColumn = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_addColumn.sizePolicy().hasHeightForWidth())
        self.pushButton_addColumn.setSizePolicy(sizePolicy)
        self.pushButton_addColumn.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_addColumn.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_addColumn.setObjectName(_fromUtf8("pushButton_addColumn"))
        self.gridLayout_2.addWidget(self.pushButton_addColumn, 4, 2, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_2.addItem(spacerItem10, 2, 9, 1, 1)
        self.label_ele_per_second = QtGui.QLabel(self.centralwidget)
        self.label_ele_per_second.setMinimumSize(QtCore.QSize(0, 20))
        self.label_ele_per_second.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_ele_per_second.setIndent(10)
        self.label_ele_per_second.setObjectName(_fromUtf8("label_ele_per_second"))
        self.gridLayout_2.addWidget(self.label_ele_per_second, 3, 0, 1, 1)
        self.label_separator = QtGui.QLabel(self.centralwidget)
        self.label_separator.setMinimumSize(QtCore.QSize(0, 20))
        self.label_separator.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_separator.setIndent(10)
        self.label_separator.setObjectName(_fromUtf8("label_separator"))
        self.gridLayout_2.addWidget(self.label_separator, 2, 0, 1, 1)
        self.lineEdit_separator = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_separator.sizePolicy().hasHeightForWidth())
        self.lineEdit_separator.setSizePolicy(sizePolicy)
        self.lineEdit_separator.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_separator.setMaximumSize(QtCore.QSize(16777215, 40))
        self.lineEdit_separator.setObjectName(_fromUtf8("lineEdit_separator"))
        self.gridLayout_2.addWidget(self.lineEdit_separator, 2, 1, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_2.addItem(spacerItem11, 0, 9, 1, 1)
        self.lineEdit_Action = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_Action.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_Action.setMaximumSize(QtCore.QSize(16777215, 40))
        self.lineEdit_Action.setObjectName(_fromUtf8("lineEdit_Action"))
        self.gridLayout_2.addWidget(self.lineEdit_Action, 7, 1, 1, 1)
        self.label_input_file_preview = QtGui.QLabel(self.centralwidget)
        self.label_input_file_preview.setMinimumSize(QtCore.QSize(0, 20))
        self.label_input_file_preview.setMaximumSize(QtCore.QSize(120, 40))
        self.label_input_file_preview.setIndent(10)
        self.label_input_file_preview.setObjectName(_fromUtf8("label_input_file_preview"))
        self.gridLayout_2.addWidget(self.label_input_file_preview, 0, 0, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem12, 0, 3, 1, 1)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_2.addItem(spacerItem13, 8, 9, 2, 1)
        self.tableWidget_input_preview = QtGui.QTableWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_input_preview.sizePolicy().hasHeightForWidth())
        self.tableWidget_input_preview.setSizePolicy(sizePolicy)
        self.tableWidget_input_preview.setMinimumSize(QtCore.QSize(0, 20))
        self.tableWidget_input_preview.setMaximumSize(QtCore.QSize(16777215, 160))
        self.tableWidget_input_preview.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget_input_preview.setObjectName(_fromUtf8("tableWidget_input_preview"))
        self.tableWidget_input_preview.setColumnCount(0)
        self.tableWidget_input_preview.setRowCount(0)
        self.gridLayout_2.addWidget(self.tableWidget_input_preview, 1, 0, 1, 9)
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_2.addItem(spacerItem14, 1, 9, 1, 1)
        spacerItem15 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_2.addItem(spacerItem15, 8, 0, 2, 7)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        spacerItem16 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem16, 1, 0, 1, 1)
        ImportSignalFromELANWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(ImportSignalFromELANWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        ImportSignalFromELANWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(ImportSignalFromELANWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        ImportSignalFromELANWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ImportSignalFromELANWindow)
        QtCore.QMetaObject.connectSlotsByName(ImportSignalFromELANWindow)

    def retranslateUi(self, ImportSignalFromELANWindow):
        ImportSignalFromELANWindow.setWindowTitle(_translate("ImportSignalFromELANWindow", "Import a Signal from ELAN file", None))
        self.pushButton_Import.setText(_translate("ImportSignalFromELANWindow", "Import", None))
        self.label_columns_names.setText(_translate("ImportSignalFromELANWindow", "Define the columns names :", None))
        self.label_actor.setText(_translate("ImportSignalFromELANWindow", "Define the Actor label : ", None))
        self.label_action.setText(_translate("ImportSignalFromELANWindow", "Define the Action label : \n"
"(to select all Actions, type \"all\")", None))
        self.pushButton_removeColumn.setText(_translate("ImportSignalFromELANWindow", "-", None))
        self.pushButton_addColumn.setText(_translate("ImportSignalFromELANWindow", "+", None))
        self.label_ele_per_second.setText(_translate("ImportSignalFromELANWindow", "Define the number of element \n"
"wanted per second :", None))
        self.label_separator.setText(_translate("ImportSignalFromELANWindow", "Define the column separator : ", None))
        self.label_input_file_preview.setText(_translate("ImportSignalFromELANWindow", "Input file preview : ", None))

