# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_MainWindow.ui'
#
# Created: Mon Jul 20 10:32:31 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1300, 800)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(100000, 100000))
        MainWindow.setSizeIncrement(QtCore.QSize(0, 0))
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_8 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setToolTip(_fromUtf8(""))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_start = QtGui.QWidget()
        self.tab_start.setObjectName(_fromUtf8("tab_start"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tab_start)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem, 0, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem1, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.tab_start)
        self.label_5.setMinimumSize(QtCore.QSize(165, 65))
        self.label_5.setMaximumSize(QtCore.QSize(330, 130))
        self.label_5.setText(_fromUtf8(""))
        self.label_5.setPixmap(QtGui.QPixmap(_fromUtf8(":/logos/images/logo_isir.jpg")))
        self.label_5.setScaledContents(True)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_9.addWidget(self.label_5, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_6 = QtGui.QLabel(self.tab_start)
        self.label_6.setMinimumSize(QtCore.QSize(165, 65))
        self.label_6.setMaximumSize(QtCore.QSize(330, 130))
        self.label_6.setText(_fromUtf8(""))
        self.label_6.setPixmap(QtGui.QPixmap(_fromUtf8(":/logos/images/logo_UPMC.png")))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_9.addWidget(self.label_6, 0, 4, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab_start)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setIndent(10)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_9.addWidget(self.label_2, 4, 0, 1, 5)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_9.addItem(spacerItem2, 3, 0, 1, 5)
        self.label = QtGui.QLabel(self.tab_start)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        self.label.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_9.addWidget(self.label, 2, 0, 1, 5)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_9.addItem(spacerItem3, 7, 0, 1, 5)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_9.addItem(spacerItem4, 5, 0, 1, 5)
        self.label_4 = QtGui.QLabel(self.tab_start)
        self.label_4.setMinimumSize(QtCore.QSize(165, 65))
        self.label_4.setMaximumSize(QtCore.QSize(330, 130))
        self.label_4.setText(_fromUtf8(""))
        self.label_4.setPixmap(QtGui.QPixmap(_fromUtf8(":/logos/images/logo_smart_labex.jpg")))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_9.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.tab_start)
        self.label_3.setMinimumSize(QtCore.QSize(0, 20))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_9.addWidget(self.label_3, 9, 1, 1, 3)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_9.addItem(spacerItem5, 1, 0, 1, 5)
        self.pushButton_start = QtGui.QPushButton(self.tab_start)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_start.sizePolicy().hasHeightForWidth())
        self.pushButton_start.setSizePolicy(sizePolicy)
        self.pushButton_start.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_start.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_start.setFont(font)
        self.pushButton_start.setObjectName(_fromUtf8("pushButton_start"))
        self.gridLayout_9.addWidget(self.pushButton_start, 6, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_9 = QtGui.QLabel(self.tab_start)
        self.label_9.setMinimumSize(QtCore.QSize(0, 20))
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_9.setIndent(10)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_9.addWidget(self.label_9, 8, 0, 1, 5)
        self.gridLayout_7.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_start, _fromUtf8(""))
        self.tab_signals = QtGui.QWidget()
        self.tab_signals.setToolTip(_fromUtf8(""))
        self.tab_signals.setObjectName(_fromUtf8("tab_signals"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_signals)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem6, 2, 0, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_existing_signals = QtGui.QLabel(self.tab_signals)
        self.label_existing_signals.setMinimumSize(QtCore.QSize(0, 20))
        self.label_existing_signals.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_existing_signals.setFont(font)
        self.label_existing_signals.setIndent(10)
        self.label_existing_signals.setObjectName(_fromUtf8("label_existing_signals"))
        self.gridLayout_4.addWidget(self.label_existing_signals, 4, 0, 1, 5)
        self.pushButton_remove_signal = QtGui.QPushButton(self.tab_signals)
        self.pushButton_remove_signal.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_remove_signal.sizePolicy().hasHeightForWidth())
        self.pushButton_remove_signal.setSizePolicy(sizePolicy)
        self.pushButton_remove_signal.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_remove_signal.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_remove_signal.setFont(font)
        self.pushButton_remove_signal.setObjectName(_fromUtf8("pushButton_remove_signal"))
        self.gridLayout_4.addWidget(self.pushButton_remove_signal, 5, 2, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem7, 5, 4, 1, 1)
        self.pushButton_edit_signal = QtGui.QPushButton(self.tab_signals)
        self.pushButton_edit_signal.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_edit_signal.sizePolicy().hasHeightForWidth())
        self.pushButton_edit_signal.setSizePolicy(sizePolicy)
        self.pushButton_edit_signal.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_edit_signal.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_edit_signal.setFont(font)
        self.pushButton_edit_signal.setObjectName(_fromUtf8("pushButton_edit_signal"))
        self.gridLayout_4.addWidget(self.pushButton_edit_signal, 5, 3, 1, 1)
        self.tableWidget_exisitng_signals = QtGui.QTableWidget(self.tab_signals)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_exisitng_signals.sizePolicy().hasHeightForWidth())
        self.tableWidget_exisitng_signals.setSizePolicy(sizePolicy)
        self.tableWidget_exisitng_signals.setMinimumSize(QtCore.QSize(0, 20))
        self.tableWidget_exisitng_signals.setMaximumSize(QtCore.QSize(16777215, 600))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableWidget_exisitng_signals.setFont(font)
        self.tableWidget_exisitng_signals.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget_exisitng_signals.setObjectName(_fromUtf8("tableWidget_exisitng_signals"))
        self.tableWidget_exisitng_signals.setColumnCount(0)
        self.tableWidget_exisitng_signals.setRowCount(0)
        self.gridLayout_4.addWidget(self.tableWidget_exisitng_signals, 6, 1, 1, 6)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_4.addItem(spacerItem8, 6, 0, 1, 1)
        self.pushButton_add_signal = QtGui.QPushButton(self.tab_signals)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_add_signal.sizePolicy().hasHeightForWidth())
        self.pushButton_add_signal.setSizePolicy(sizePolicy)
        self.pushButton_add_signal.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_add_signal.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_add_signal.setFont(font)
        self.pushButton_add_signal.setObjectName(_fromUtf8("pushButton_add_signal"))
        self.gridLayout_4.addWidget(self.pushButton_add_signal, 5, 1, 1, 1)
        self.label_title_tab_signals = QtGui.QLabel(self.tab_signals)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_title_tab_signals.sizePolicy().hasHeightForWidth())
        self.label_title_tab_signals.setSizePolicy(sizePolicy)
        self.label_title_tab_signals.setMinimumSize(QtCore.QSize(0, 40))
        self.label_title_tab_signals.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_title_tab_signals.setFont(font)
        self.label_title_tab_signals.setObjectName(_fromUtf8("label_title_tab_signals"))
        self.gridLayout_4.addWidget(self.label_title_tab_signals, 0, 0, 1, 8)
        self.label_tab_signals_description = QtGui.QLabel(self.tab_signals)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_tab_signals_description.sizePolicy().hasHeightForWidth())
        self.label_tab_signals_description.setSizePolicy(sizePolicy)
        self.label_tab_signals_description.setMinimumSize(QtCore.QSize(0, 20))
        self.label_tab_signals_description.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_tab_signals_description.setFont(font)
        self.label_tab_signals_description.setIndent(10)
        self.label_tab_signals_description.setObjectName(_fromUtf8("label_tab_signals_description"))
        self.gridLayout_4.addWidget(self.label_tab_signals_description, 2, 0, 1, 8)
        self.label_8 = QtGui.QLabel(self.tab_signals)
        self.label_8.setMinimumSize(QtCore.QSize(0, 20))
        self.label_8.setMaximumSize(QtCore.QSize(100, 40))
        self.label_8.setText(_fromUtf8(""))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 5, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.tab_signals)
        self.label_7.setMinimumSize(QtCore.QSize(0, 20))
        self.label_7.setMaximumSize(QtCore.QSize(100, 40))
        self.label_7.setText(_fromUtf8(""))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_4.addWidget(self.label_7, 5, 7, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_4.addItem(spacerItem9, 5, 5, 1, 2)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_4.addItem(spacerItem10, 1, 0, 1, 8)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_4.addItem(spacerItem11, 3, 0, 1, 8)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_4.addItem(spacerItem12, 4, 5, 1, 3)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_4.addItem(spacerItem13, 6, 7, 1, 1)
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_4.addItem(spacerItem14, 7, 0, 1, 8)
        self.gridLayout_5.addLayout(self.gridLayout_4, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_signals, _fromUtf8(""))
        self.tab_methods = QtGui.QWidget()
        self.tab_methods.setToolTip(_fromUtf8(""))
        self.tab_methods.setObjectName(_fromUtf8("tab_methods"))
        self.gridLayout = QtGui.QGridLayout(self.tab_methods)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem15 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem15, 1, 0, 1, 2)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.button_No = QtGui.QPushButton(self.tab_methods)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_No.sizePolicy().hasHeightForWidth())
        self.button_No.setSizePolicy(sizePolicy)
        self.button_No.setMinimumSize(QtCore.QSize(0, 60))
        self.button_No.setMaximumSize(QtCore.QSize(200, 80))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.button_No.setFont(font)
        self.button_No.setObjectName(_fromUtf8("button_No"))
        self.gridLayout_2.addWidget(self.button_No, 4, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_title_tab_methods = QtGui.QLabel(self.tab_methods)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_title_tab_methods.sizePolicy().hasHeightForWidth())
        self.label_title_tab_methods.setSizePolicy(sizePolicy)
        self.label_title_tab_methods.setMinimumSize(QtCore.QSize(0, 40))
        self.label_title_tab_methods.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_title_tab_methods.setFont(font)
        self.label_title_tab_methods.setObjectName(_fromUtf8("label_title_tab_methods"))
        self.gridLayout_2.addWidget(self.label_title_tab_methods, 0, 0, 1, 6)
        self.label_choose_method = QtGui.QLabel(self.tab_methods)
        self.label_choose_method.setMinimumSize(QtCore.QSize(0, 20))
        self.label_choose_method.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_choose_method.setFont(font)
        self.label_choose_method.setIndent(10)
        self.label_choose_method.setObjectName(_fromUtf8("label_choose_method"))
        self.gridLayout_2.addWidget(self.label_choose_method, 6, 0, 1, 2)
        spacerItem16 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_2.addItem(spacerItem16, 3, 0, 1, 6)
        self.button_Yes = QtGui.QPushButton(self.tab_methods)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_Yes.sizePolicy().hasHeightForWidth())
        self.button_Yes.setSizePolicy(sizePolicy)
        self.button_Yes.setMinimumSize(QtCore.QSize(0, 60))
        self.button_Yes.setMaximumSize(QtCore.QSize(200, 80))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.button_Yes.setFont(font)
        self.button_Yes.setObjectName(_fromUtf8("button_Yes"))
        self.gridLayout_2.addWidget(self.button_Yes, 4, 1, 1, 1, QtCore.Qt.AlignHCenter)
        spacerItem17 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_2.addItem(spacerItem17, 1, 0, 1, 6)
        self.label_tab_methods_description = QtGui.QLabel(self.tab_methods)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_tab_methods_description.sizePolicy().hasHeightForWidth())
        self.label_tab_methods_description.setSizePolicy(sizePolicy)
        self.label_tab_methods_description.setMinimumSize(QtCore.QSize(0, 20))
        self.label_tab_methods_description.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_tab_methods_description.setFont(font)
        self.label_tab_methods_description.setIndent(10)
        self.label_tab_methods_description.setObjectName(_fromUtf8("label_tab_methods_description"))
        self.gridLayout_2.addWidget(self.label_tab_methods_description, 2, 0, 1, 6)
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem18, 4, 5, 1, 1)
        spacerItem19 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_2.addItem(spacerItem19, 6, 3, 1, 1)
        self.comboBox_methods = QtGui.QComboBox(self.tab_methods)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_methods.sizePolicy().hasHeightForWidth())
        self.comboBox_methods.setSizePolicy(sizePolicy)
        self.comboBox_methods.setMinimumSize(QtCore.QSize(0, 20))
        self.comboBox_methods.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_methods.setFont(font)
        self.comboBox_methods.setObjectName(_fromUtf8("comboBox_methods"))
        self.gridLayout_2.addWidget(self.comboBox_methods, 7, 0, 1, 2)
        spacerItem20 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_2.addItem(spacerItem20, 7, 3, 1, 1)
        spacerItem21 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_2.addItem(spacerItem21, 5, 0, 1, 3)
        spacerItem22 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem22, 4, 3, 1, 1)
        spacerItem23 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem23, 4, 0, 1, 1)
        spacerItem24 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_2.addItem(spacerItem24, 5, 4, 8, 2)
        self.label_method_selected = QtGui.QLabel(self.tab_methods)
        self.label_method_selected.setText(_fromUtf8(""))
        self.label_method_selected.setAlignment(QtCore.Qt.AlignCenter)
        self.label_method_selected.setObjectName(_fromUtf8("label_method_selected"))
        self.gridLayout_2.addWidget(self.label_method_selected, 9, 2, 4, 2)
        spacerItem25 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_2.addItem(spacerItem25, 9, 0, 4, 1)
        self.pushButton_valid_method = QtGui.QPushButton(self.tab_methods)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_valid_method.sizePolicy().hasHeightForWidth())
        self.pushButton_valid_method.setSizePolicy(sizePolicy)
        self.pushButton_valid_method.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_valid_method.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_valid_method.setFont(font)
        self.pushButton_valid_method.setObjectName(_fromUtf8("pushButton_valid_method"))
        self.gridLayout_2.addWidget(self.pushButton_valid_method, 8, 2, 1, 1, QtCore.Qt.AlignHCenter)
        spacerItem26 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_2.addItem(spacerItem26, 5, 3, 1, 1)
        self.label_method = QtGui.QLabel(self.tab_methods)
        self.label_method.setMinimumSize(QtCore.QSize(0, 20))
        self.label_method.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_method.setFont(font)
        self.label_method.setIndent(10)
        self.label_method.setObjectName(_fromUtf8("label_method"))
        self.gridLayout_2.addWidget(self.label_method, 9, 1, 4, 1)
        spacerItem27 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_2.addItem(spacerItem27, 8, 3, 1, 1)
        spacerItem28 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem28, 4, 2, 1, 1)
        spacerItem29 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_2.addItem(spacerItem29, 13, 0, 1, 6)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 2)
        self.tabWidget.addTab(self.tab_methods, _fromUtf8(""))
        self.tab_compute = QtGui.QWidget()
        self.tab_compute.setObjectName(_fromUtf8("tab_compute"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_compute)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        spacerItem30 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_6.addItem(spacerItem30, 12, 5, 1, 1)
        self.label_selected_method = QtGui.QLabel(self.tab_compute)
        self.label_selected_method.setMinimumSize(QtCore.QSize(0, 20))
        self.label_selected_method.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_selected_method.setSizeIncrement(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_selected_method.setFont(font)
        self.label_selected_method.setText(_fromUtf8(""))
        self.label_selected_method.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_selected_method.setIndent(10)
        self.label_selected_method.setObjectName(_fromUtf8("label_selected_method"))
        self.gridLayout_6.addWidget(self.label_selected_method, 4, 1, 1, 2)
        spacerItem31 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_6.addItem(spacerItem31, 4, 5, 1, 1)
        spacerItem32 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_6.addItem(spacerItem32, 3, 0, 1, 6)
        self.label_select_parameters = QtGui.QLabel(self.tab_compute)
        self.label_select_parameters.setMinimumSize(QtCore.QSize(0, 20))
        self.label_select_parameters.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_select_parameters.setFont(font)
        self.label_select_parameters.setIndent(0)
        self.label_select_parameters.setObjectName(_fromUtf8("label_select_parameters"))
        self.gridLayout_6.addWidget(self.label_select_parameters, 5, 1, 1, 1)
        spacerItem33 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_6.addItem(spacerItem33, 5, 5, 1, 1)
        self.formLayout_method_parameters = QtGui.QFormLayout()
        self.formLayout_method_parameters.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_method_parameters.setObjectName(_fromUtf8("formLayout_method_parameters"))
        self.gridLayout_6.addLayout(self.formLayout_method_parameters, 6, 1, 2, 1)
        self.label_title_tab_compute = QtGui.QLabel(self.tab_compute)
        self.label_title_tab_compute.setMinimumSize(QtCore.QSize(0, 40))
        self.label_title_tab_compute.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_title_tab_compute.setFont(font)
        self.label_title_tab_compute.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title_tab_compute.setObjectName(_fromUtf8("label_title_tab_compute"))
        self.gridLayout_6.addWidget(self.label_title_tab_compute, 0, 0, 1, 6)
        self.label_available_signals = QtGui.QLabel(self.tab_compute)
        self.label_available_signals.setMinimumSize(QtCore.QSize(0, 20))
        self.label_available_signals.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_available_signals.setFont(font)
        self.label_available_signals.setIndent(0)
        self.label_available_signals.setObjectName(_fromUtf8("label_available_signals"))
        self.gridLayout_6.addWidget(self.label_available_signals, 5, 4, 1, 1)
        spacerItem34 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_6.addItem(spacerItem34, 7, 5, 1, 1)
        spacerItem35 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_6.addItem(spacerItem35, 1, 0, 1, 6)
        spacerItem36 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_6.addItem(spacerItem36, 8, 5, 1, 1)
        spacerItem37 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_6.addItem(spacerItem37, 6, 5, 1, 1)
        self.label_tab_compute_description = QtGui.QLabel(self.tab_compute)
        self.label_tab_compute_description.setMinimumSize(QtCore.QSize(0, 20))
        self.label_tab_compute_description.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_tab_compute_description.setFont(font)
        self.label_tab_compute_description.setIndent(10)
        self.label_tab_compute_description.setObjectName(_fromUtf8("label_tab_compute_description"))
        self.gridLayout_6.addWidget(self.label_tab_compute_description, 2, 0, 1, 6)
        self.label_method_2 = QtGui.QLabel(self.tab_compute)
        self.label_method_2.setMinimumSize(QtCore.QSize(0, 20))
        self.label_method_2.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_method_2.setFont(font)
        self.label_method_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_method_2.setIndent(0)
        self.label_method_2.setObjectName(_fromUtf8("label_method_2"))
        self.gridLayout_6.addWidget(self.label_method_2, 4, 0, 1, 1)
        self.lineEdit_output_folder = QtGui.QLineEdit(self.tab_compute)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_output_folder.sizePolicy().hasHeightForWidth())
        self.lineEdit_output_folder.setSizePolicy(sizePolicy)
        self.lineEdit_output_folder.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_output_folder.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_output_folder.setFont(font)
        self.lineEdit_output_folder.setObjectName(_fromUtf8("lineEdit_output_folder"))
        self.gridLayout_6.addWidget(self.lineEdit_output_folder, 10, 2, 2, 2)
        self.pushButton_browse_output_folder = QtGui.QPushButton(self.tab_compute)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_browse_output_folder.sizePolicy().hasHeightForWidth())
        self.pushButton_browse_output_folder.setSizePolicy(sizePolicy)
        self.pushButton_browse_output_folder.setMinimumSize(QtCore.QSize(20, 20))
        self.pushButton_browse_output_folder.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_browse_output_folder.setFont(font)
        self.pushButton_browse_output_folder.setObjectName(_fromUtf8("pushButton_browse_output_folder"))
        self.gridLayout_6.addWidget(self.pushButton_browse_output_folder, 10, 4, 2, 1)
        spacerItem38 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_6.addItem(spacerItem38, 5, 0, 5, 1)
        spacerItem39 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_6.addItem(spacerItem39, 13, 5, 1, 1)
        spacerItem40 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_6.addItem(spacerItem40, 10, 5, 2, 1)
        spacerItem41 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem41, 10, 0, 4, 1)
        spacerItem42 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem42, 9, 1, 1, 5)
        self.listWidget_available_signals = QtGui.QListWidget(self.tab_compute)
        self.listWidget_available_signals.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_available_signals.sizePolicy().hasHeightForWidth())
        self.listWidget_available_signals.setSizePolicy(sizePolicy)
        self.listWidget_available_signals.setMinimumSize(QtCore.QSize(0, 20))
        self.listWidget_available_signals.setMaximumSize(QtCore.QSize(16777215, 200))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.listWidget_available_signals.setFont(font)
        self.listWidget_available_signals.setFrameShape(QtGui.QFrame.NoFrame)
        self.listWidget_available_signals.setLineWidth(0)
        self.listWidget_available_signals.setUniformItemSizes(True)
        self.listWidget_available_signals.setObjectName(_fromUtf8("listWidget_available_signals"))
        self.gridLayout_6.addWidget(self.listWidget_available_signals, 6, 4, 2, 1)
        self.pushButton_save_file = QtGui.QPushButton(self.tab_compute)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_save_file.sizePolicy().hasHeightForWidth())
        self.pushButton_save_file.setSizePolicy(sizePolicy)
        self.pushButton_save_file.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_save_file.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_save_file.setFont(font)
        self.pushButton_save_file.setObjectName(_fromUtf8("pushButton_save_file"))
        self.gridLayout_6.addWidget(self.pushButton_save_file, 13, 4, 1, 1)
        self.label_choose_output = QtGui.QLabel(self.tab_compute)
        self.label_choose_output.setMinimumSize(QtCore.QSize(0, 20))
        self.label_choose_output.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_choose_output.setFont(font)
        self.label_choose_output.setIndent(10)
        self.label_choose_output.setObjectName(_fromUtf8("label_choose_output"))
        self.gridLayout_6.addWidget(self.label_choose_output, 10, 1, 2, 1)
        self.lineEdit_output_filename = QtGui.QLineEdit(self.tab_compute)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_output_filename.sizePolicy().hasHeightForWidth())
        self.lineEdit_output_filename.setSizePolicy(sizePolicy)
        self.lineEdit_output_filename.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_output_filename.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_output_filename.setFont(font)
        self.lineEdit_output_filename.setObjectName(_fromUtf8("lineEdit_output_filename"))
        self.gridLayout_6.addWidget(self.lineEdit_output_filename, 12, 2, 1, 2)
        self.label_choose_output_file = QtGui.QLabel(self.tab_compute)
        self.label_choose_output_file.setMinimumSize(QtCore.QSize(0, 20))
        self.label_choose_output_file.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_choose_output_file.setFont(font)
        self.label_choose_output_file.setIndent(10)
        self.label_choose_output_file.setObjectName(_fromUtf8("label_choose_output_file"))
        self.gridLayout_6.addWidget(self.label_choose_output_file, 12, 1, 1, 1)
        spacerItem43 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_6.addItem(spacerItem43, 14, 0, 1, 6)
        self.pushButton_compute_method = QtGui.QPushButton(self.tab_compute)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_compute_method.sizePolicy().hasHeightForWidth())
        self.pushButton_compute_method.setSizePolicy(sizePolicy)
        self.pushButton_compute_method.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_compute_method.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_compute_method.setFont(font)
        self.pushButton_compute_method.setObjectName(_fromUtf8("pushButton_compute_method"))
        self.gridLayout_6.addWidget(self.pushButton_compute_method, 8, 2, 1, 2, QtCore.Qt.AlignHCenter)
        self.gridLayout_3.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        spacerItem44 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_3.addItem(spacerItem44, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_compute, _fromUtf8(""))
        self.gridLayout_8.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Open SMART Time Interface", None))
        self.label_2.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">With SyncPy, you can study synchrony in interaction thanks to several methods implemented in python. </p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">This current interface offer the possibility to simply try these methods with real signals. </p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The window is divided in tree tabs : </p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- Signals tab : import and edit your signals </p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- Methods tab : choose the desired method from list</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- Compute tab : Test the selected method with defined signals and record the result </p></body></html>", None))
        self.label.setText(_translate("MainWindow", "Welcome in the SyncPy library Interface !", None))
        self.label_3.setText(_translate("MainWindow", "© Copyright 2015, Giovanna Varni, Marie Avril. Created using PyQt.", None))
        self.pushButton_start.setText(_translate("MainWindow", "Let\'s go !", None))
        self.label_9.setText(_translate("MainWindow", "References : ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_start), _translate("MainWindow", "Home", None))
        self.label_existing_signals.setText(_translate("MainWindow", "Existing signals : ", None))
        self.pushButton_remove_signal.setToolTip(_translate("MainWindow", "<html><head/><body><p>Remove a selected signal from the list</p></body></html>", None))
        self.pushButton_remove_signal.setText(_translate("MainWindow", "Remove", None))
        self.pushButton_edit_signal.setToolTip(_translate("MainWindow", "<html><head/><body><p>Edit a signal selected in the list</p></body></html>", None))
        self.pushButton_edit_signal.setText(_translate("MainWindow", "Edit", None))
        self.tableWidget_exisitng_signals.setToolTip(_translate("MainWindow", "<html><head/><body><p>List of exisiting signals</p></body></html>", None))
        self.pushButton_add_signal.setToolTip(_translate("MainWindow", "<html><head/><body><p>Add a new signal in the list</p></body></html>", None))
        self.pushButton_add_signal.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None))
        self.pushButton_add_signal.setText(_translate("MainWindow", "Add", None))
        self.label_title_tab_signals.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Signals selection</p></body></html>", None))
        self.label_tab_signals_description.setText(_translate("MainWindow", "In this tab, you can add signals you want to analyze. ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_signals), _translate("MainWindow", "Signals", None))
        self.button_No.setToolTip(_translate("MainWindow", "<html><head/><body><p>Open a window to help the method\'s choice</p></body></html>", None))
        self.button_No.setText(_translate("MainWindow", "I don\'t  know \n"
"what method I want", None))
        self.label_title_tab_methods.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Synchrony Method selection</p></body></html>", None))
        self.label_choose_method.setText(_translate("MainWindow", "Choose the wanted method : ", None))
        self.button_Yes.setToolTip(_translate("MainWindow", "<html><head/><body><p>Select a method from the complete list</p></body></html>", None))
        self.button_Yes.setText(_translate("MainWindow", "I know \n"
"what method I want", None))
        self.label_tab_methods_description.setText(_translate("MainWindow", "In this tab, you can choose which method you want to use. ", None))
        self.comboBox_methods.setToolTip(_translate("MainWindow", "<html><head/><body><p>Methods list</p></body></html>", None))
        self.pushButton_valid_method.setToolTip(_translate("MainWindow", "<html><head/><body><p>Select the current method</p></body></html>", None))
        self.pushButton_valid_method.setText(_translate("MainWindow", "Ok", None))
        self.label_method.setText(_translate("MainWindow", "Method selected : ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_methods), _translate("MainWindow", "Methods", None))
        self.label_selected_method.setToolTip(_translate("MainWindow", "<html><head/><body><p>Selected method from Methods tab</p></body></html>", None))
        self.label_select_parameters.setText(_translate("MainWindow", "Define parameters : ", None))
        self.label_title_tab_compute.setText(_translate("MainWindow", "Method Computation", None))
        self.label_available_signals.setText(_translate("MainWindow", "Select signals : ", None))
        self.label_tab_compute_description.setText(_translate("MainWindow", "In this tab, you can compute the selected method with the available signals", None))
        self.label_method_2.setText(_translate("MainWindow", "Selected method : ", None))
        self.lineEdit_output_folder.setToolTip(_translate("MainWindow", "<html><head/><body><p>Folder path to the result file</p></body></html>", None))
        self.pushButton_browse_output_folder.setToolTip(_translate("MainWindow", "<html><head/><body><p>Browse folders</p></body></html>", None))
        self.pushButton_browse_output_folder.setText(_translate("MainWindow", "...", None))
        self.listWidget_available_signals.setToolTip(_translate("MainWindow", "<html><head/><body><p>List of available signals according to the selected method properties</p></body></html>", None))
        self.pushButton_save_file.setToolTip(_translate("MainWindow", "<html><head/><body><p>Save the result file</p></body></html>", None))
        self.pushButton_save_file.setText(_translate("MainWindow", "Save", None))
        self.label_choose_output.setText(_translate("MainWindow", "Choose an output folder : ", None))
        self.lineEdit_output_filename.setToolTip(_translate("MainWindow", "<html><head/><body><p>Name of result file</p></body></html>", None))
        self.label_choose_output_file.setText(_translate("MainWindow", "Define output file name : ", None))
        self.pushButton_compute_method.setToolTip(_translate("MainWindow", "<html><head/><body><p>Launch selected method computation with defined signals and parameters</p></body></html>", None))
        self.pushButton_compute_method.setText(_translate("MainWindow", "Compute", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_compute), _translate("MainWindow", "Compute", None))

import ressource_rc
