# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_MethodSelectionWindow.ui'
#
# Created: Fri Jul 03 14:10:44 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MethodSelectionWindow(object):
    def setupUi(self, MethodSelectionWindow):
        MethodSelectionWindow.setObjectName(_fromUtf8("MethodSelectionWindow"))
        MethodSelectionWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setPointSize(10)
        MethodSelectionWindow.setFont(font)
        self.centralwidget = QtGui.QWidget(MethodSelectionWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.gridLayout_select_data = QtGui.QGridLayout()
        self.gridLayout_select_data.setObjectName(_fromUtf8("gridLayout_select_data"))
        self.radioButton_data_1b = QtGui.QRadioButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_data_1b.sizePolicy().hasHeightForWidth())
        self.radioButton_data_1b.setSizePolicy(sizePolicy)
        self.radioButton_data_1b.setMinimumSize(QtCore.QSize(0, 20))
        self.radioButton_data_1b.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_data_1b.setFont(font)
        self.radioButton_data_1b.setChecked(False)
        self.radioButton_data_1b.setAutoExclusive(False)
        self.radioButton_data_1b.setObjectName(_fromUtf8("radioButton_data_1b"))
        self.gridLayout_select_data.addWidget(self.radioButton_data_1b, 1, 2, 1, 1)
        self.radioButton_data_3b = QtGui.QRadioButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_data_3b.sizePolicy().hasHeightForWidth())
        self.radioButton_data_3b.setSizePolicy(sizePolicy)
        self.radioButton_data_3b.setMinimumSize(QtCore.QSize(0, 20))
        self.radioButton_data_3b.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_data_3b.setFont(font)
        self.radioButton_data_3b.setAutoExclusive(False)
        self.radioButton_data_3b.setObjectName(_fromUtf8("radioButton_data_3b"))
        self.gridLayout_select_data.addWidget(self.radioButton_data_3b, 3, 2, 1, 1)
        self.pushButton_valid_method_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_valid_method_2.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_valid_method_2.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_valid_method_2.setFont(font)
        self.pushButton_valid_method_2.setObjectName(_fromUtf8("pushButton_valid_method_2"))
        self.gridLayout_select_data.addWidget(self.pushButton_valid_method_2, 11, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.radioButton_data_2a = QtGui.QRadioButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_data_2a.sizePolicy().hasHeightForWidth())
        self.radioButton_data_2a.setSizePolicy(sizePolicy)
        self.radioButton_data_2a.setMinimumSize(QtCore.QSize(0, 20))
        self.radioButton_data_2a.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_data_2a.setFont(font)
        self.radioButton_data_2a.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_data_2a.setChecked(True)
        self.radioButton_data_2a.setAutoExclusive(False)
        self.radioButton_data_2a.setObjectName(_fromUtf8("radioButton_data_2a"))
        self.gridLayout_select_data.addWidget(self.radioButton_data_2a, 2, 1, 1, 1)
        self.comboBox_machinelearning_methods = QtGui.QComboBox(self.centralwidget)
        self.comboBox_machinelearning_methods.setMinimumSize(QtCore.QSize(0, 20))
        self.comboBox_machinelearning_methods.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_machinelearning_methods.setFont(font)
        self.comboBox_machinelearning_methods.setObjectName(_fromUtf8("comboBox_machinelearning_methods"))
        self.gridLayout_select_data.addWidget(self.comboBox_machinelearning_methods, 9, 2, 1, 1)
        self.radioButton_data_1a = QtGui.QRadioButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_data_1a.sizePolicy().hasHeightForWidth())
        self.radioButton_data_1a.setSizePolicy(sizePolicy)
        self.radioButton_data_1a.setMinimumSize(QtCore.QSize(0, 20))
        self.radioButton_data_1a.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_data_1a.setFont(font)
        self.radioButton_data_1a.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_data_1a.setChecked(True)
        self.radioButton_data_1a.setAutoExclusive(False)
        self.radioButton_data_1a.setObjectName(_fromUtf8("radioButton_data_1a"))
        self.gridLayout_select_data.addWidget(self.radioButton_data_1a, 1, 1, 1, 1)
        self.comboBox_linear_methods = QtGui.QComboBox(self.centralwidget)
        self.comboBox_linear_methods.setMinimumSize(QtCore.QSize(0, 20))
        self.comboBox_linear_methods.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_linear_methods.setFont(font)
        self.comboBox_linear_methods.setObjectName(_fromUtf8("comboBox_linear_methods"))
        self.gridLayout_select_data.addWidget(self.comboBox_linear_methods, 7, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_select_data.addItem(spacerItem1, 9, 3, 1, 1)
        self.radioButton_data_2b = QtGui.QRadioButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_data_2b.sizePolicy().hasHeightForWidth())
        self.radioButton_data_2b.setSizePolicy(sizePolicy)
        self.radioButton_data_2b.setMinimumSize(QtCore.QSize(0, 20))
        self.radioButton_data_2b.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_data_2b.setFont(font)
        self.radioButton_data_2b.setAutoExclusive(False)
        self.radioButton_data_2b.setObjectName(_fromUtf8("radioButton_data_2b"))
        self.gridLayout_select_data.addWidget(self.radioButton_data_2b, 2, 2, 1, 1)
        self.comboBox_nonlinear_methods = QtGui.QComboBox(self.centralwidget)
        self.comboBox_nonlinear_methods.setMinimumSize(QtCore.QSize(0, 20))
        self.comboBox_nonlinear_methods.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_nonlinear_methods.setFont(font)
        self.comboBox_nonlinear_methods.setObjectName(_fromUtf8("comboBox_nonlinear_methods"))
        self.gridLayout_select_data.addWidget(self.comboBox_nonlinear_methods, 8, 2, 1, 1)
        self.label_machinelearning_methods = QtGui.QLabel(self.centralwidget)
        self.label_machinelearning_methods.setMinimumSize(QtCore.QSize(0, 20))
        self.label_machinelearning_methods.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_machinelearning_methods.setFont(font)
        self.label_machinelearning_methods.setIndent(10)
        self.label_machinelearning_methods.setObjectName(_fromUtf8("label_machinelearning_methods"))
        self.gridLayout_select_data.addWidget(self.label_machinelearning_methods, 9, 1, 1, 1)
        self.label_nonlinear_methods = QtGui.QLabel(self.centralwidget)
        self.label_nonlinear_methods.setMinimumSize(QtCore.QSize(0, 20))
        self.label_nonlinear_methods.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_nonlinear_methods.setFont(font)
        self.label_nonlinear_methods.setIndent(10)
        self.label_nonlinear_methods.setObjectName(_fromUtf8("label_nonlinear_methods"))
        self.gridLayout_select_data.addWidget(self.label_nonlinear_methods, 8, 1, 1, 1)
        self.radioButton_data_3a = QtGui.QRadioButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_data_3a.sizePolicy().hasHeightForWidth())
        self.radioButton_data_3a.setSizePolicy(sizePolicy)
        self.radioButton_data_3a.setMinimumSize(QtCore.QSize(0, 20))
        self.radioButton_data_3a.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_data_3a.setFont(font)
        self.radioButton_data_3a.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_data_3a.setChecked(True)
        self.radioButton_data_3a.setAutoExclusive(False)
        self.radioButton_data_3a.setObjectName(_fromUtf8("radioButton_data_3a"))
        self.gridLayout_select_data.addWidget(self.radioButton_data_3a, 3, 1, 1, 1)
        self.label_linear_methods = QtGui.QLabel(self.centralwidget)
        self.label_linear_methods.setMinimumSize(QtCore.QSize(0, 20))
        self.label_linear_methods.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_linear_methods.setFont(font)
        self.label_linear_methods.setIndent(10)
        self.label_linear_methods.setObjectName(_fromUtf8("label_linear_methods"))
        self.gridLayout_select_data.addWidget(self.label_linear_methods, 7, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_select_data.addItem(spacerItem2, 7, 3, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_select_data.addItem(spacerItem3, 8, 3, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_select_data.addItem(spacerItem4, 6, 4, 6, 1)
        self.label_select_data = QtGui.QLabel(self.centralwidget)
        self.label_select_data.setMinimumSize(QtCore.QSize(0, 20))
        self.label_select_data.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_select_data.setFont(font)
        self.label_select_data.setIndent(10)
        self.label_select_data.setObjectName(_fromUtf8("label_select_data"))
        self.gridLayout_select_data.addWidget(self.label_select_data, 0, 0, 1, 3)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_select_data.addItem(spacerItem5, 4, 0, 1, 5)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_select_data.addItem(spacerItem6, 10, 0, 1, 4)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_select_data.addItem(spacerItem7, 11, 0, 1, 3)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_select_data.addItem(spacerItem8, 0, 3, 1, 2)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_select_data.addItem(spacerItem9, 1, 3, 1, 2)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_select_data.addItem(spacerItem10, 2, 3, 1, 2)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_select_data.addItem(spacerItem11, 3, 3, 1, 2)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_select_data.addItem(spacerItem12, 5, 3, 1, 2)
        self.label_choose_method_2 = QtGui.QLabel(self.centralwidget)
        self.label_choose_method_2.setMinimumSize(QtCore.QSize(0, 20))
        self.label_choose_method_2.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_choose_method_2.setFont(font)
        self.label_choose_method_2.setIndent(10)
        self.label_choose_method_2.setObjectName(_fromUtf8("label_choose_method_2"))
        self.gridLayout_select_data.addWidget(self.label_choose_method_2, 5, 0, 1, 3)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_select_data.addItem(spacerItem13, 6, 0, 1, 4)
        self.gridLayout.addLayout(self.gridLayout_select_data, 0, 0, 1, 1)
        MethodSelectionWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MethodSelectionWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MethodSelectionWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MethodSelectionWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MethodSelectionWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MethodSelectionWindow)
        QtCore.QMetaObject.connectSlotsByName(MethodSelectionWindow)

    def retranslateUi(self, MethodSelectionWindow):
        MethodSelectionWindow.setWindowTitle(_translate("MethodSelectionWindow", "Select a Method", None))
        self.radioButton_data_1b.setText(_translate("MethodSelectionWindow", "I have data from many persons", None))
        self.radioButton_data_3b.setText(_translate("MethodSelectionWindow", "I have categorical signal", None))
        self.pushButton_valid_method_2.setText(_translate("MethodSelectionWindow", "Ok", None))
        self.radioButton_data_2a.setText(_translate("MethodSelectionWindow", "I have monovariate signal", None))
        self.radioButton_data_1a.setText(_translate("MethodSelectionWindow", "I have data from two persons", None))
        self.radioButton_data_2b.setText(_translate("MethodSelectionWindow", "I have multivariate signal", None))
        self.label_machinelearning_methods.setText(_translate("MethodSelectionWindow", "Machine Learning methods:", None))
        self.label_nonlinear_methods.setText(_translate("MethodSelectionWindow", "Non Linear methods: ", None))
        self.radioButton_data_3a.setText(_translate("MethodSelectionWindow", "I have continuous signal", None))
        self.label_linear_methods.setText(_translate("MethodSelectionWindow", "Linear methods: ", None))
        self.label_select_data.setText(_translate("MethodSelectionWindow", "Define your type of data : ", None))
        self.label_choose_method_2.setText(_translate("MethodSelectionWindow", "Choose an available method : ", None))

